# Welcome to the GT AIMS Website

title:  The Artificial Intelligence for Medicine and Healthcare Society
tagline:  The Artificial Intelligence for Medicine and Healthcare Society.
email: aimsatgt@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We are dedicated to (1) helping one another become the next generation of leaders within the field of AI for healthcare and medicine, (2) to helping curious students learn more about the field, and (3) to broadly creating a strong community around the field at Georgia Tech.
baseurl: "" # the subpath of your site
url: https://gtaims.github.io
locale: en_US
github: "https://github.com/gtaims"
twitter:
  card: summary_large_image
  username: aimsatgt
google_analytics: G-6V9MFRB4SQ
logo: /assets/images/AIMS-long.png
author: 
  twitter: aimsatgt

collections:
  groups:
    output: false
  students:
    output: false
  faculty:
    output: false
  courses:
    output: false
  publications:
    output: false

sass:
  load_paths:
      - node_modules

# Build settings
# theme: minima
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include: ["node_modules"]